services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  App\Tests\:
    resource: "../tests/*"
    exclude: "../tests/{bootstrap.php}"

  Doctrine\Common\DataFixtures\Executor\ORMExecutor: ~

  App\Tests\Tools\Loader\DoctrineFixtureLoader:
    arguments:
      $container: "@service_container"

  Symfony\Component\PasswordHasher\Hasher\UserPasswordHasher: ~
  App\Tools\Parser\ArrayParser: ~
  App\Tools\Parser\ObjectParser: ~
