knp_paginator:
  page_range: 3 # default page range used in pagination control
  default_options:
    page_name: page # page query parameter name
    sort_field_name: sort # sort field query parameter name
    sort_direction_name: direction # sort direction query parameter name
    distinct: true
  template:
    pagination: "@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig"
    sortable: "@KnpPaginator/Pagination/bootstrap_v5_fa_sortable_link.html.twig"
    filtration: "@KnpPaginator/Pagination/bootstrap_v5_filtration.html.twig"
