sentry:
  dsn: "%env(SENTRY_BACKEND_DSN)%"
  options:
    environment: "%env(SENTRY_ENVIRONMENT)%"
    before_send: "sentry.callback.before_send"
    traces_sample_rate: 0.1
    integrations:
      - 'Sentry\Integration\IgnoreErrorsIntegration'
  register_error_listener: false
  register_error_handler: false

services:
  sentry.callback.before_send:
    class: 'App\Service\Integration\Sentry'
    factory: ['@App\Service\Integration\Sentry', "getBeforeSend"]
  Sentry\Integration\IgnoreErrorsIntegration:
    arguments:
      $options:
        ignore_exceptions:
          - RuntimeException
