name: Build and Test
on: [ pull_request ]
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  HOST: test.haussmann-medias.local
  APP_PATH: /var/www/haussmann-medias
  BUILDER_TAG: haussmann-medias-main-builder
  DOCKER_COMPOSE_FILE: docker/docker-compose.test.yaml
jobs:
  build:
    if: ${{ github.actor != 'renovate[bot]' }}
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build container
        run: docker build -t ${{ env.BUILDER_TAG }} - < docker/app-builder/Dockerfile
      - name: Build
        run: docker/script/run-build.sh
      - name: Package artifact
        run: |
          mkdir /tmp/build
          tar czf /tmp/build/archive.tar.gz \
            --exclude=app/var/cache \
            --exclude=app/var/logs \
            --anchored --exclude=cache \
            *
      - name: Store artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: /tmp/build
          retention-days: 1

  code-style:
    #    if: ${{ false }}
    name: Code style checks
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: /tmp/build/
      - name: Extract archive
        run: |
          tar xzf /tmp/build/archive.tar.gz
          rm -rf /tmp/build
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build container
        run: docker build -t ${{ env.BUILDER_TAG }} - < docker/app-builder/Dockerfile
      - name: Run analyses
        run: |
          docker run -v$(pwd):${{ env.APP_PATH }} \
            -w ${{ env.APP_PATH }}/app \
            ${{ env.BUILDER_TAG }} \
            bin/phing analyze
      - name: Clean up
        run: docker rmi -f ${{ env.BUILDER_TAG }}

  phpunit:
    #    if: ${{ false }}
    name: PHPUnit tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: /tmp/build/
      - name: Extract archive
        run: |
          tar xzf /tmp/build/archive.tar.gz
          rm -rf /tmp/build
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build container
        timeout-minutes: 5
        run: |
          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} build
          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} up -d
      - name: Run tests
        run: docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} exec -T app bash -c 'bin/phing test_prepare && bin/phing coverage'
      - name: Clean up
        if: always()
        run: |
          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} down --remove-orphans --volumes
          docker rmi -f app

  behat:
    name: Behat tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: /tmp/build/
      - name: Extract archive
        run: |
          tar xzf /tmp/build/archive.tar.gz
          rm -rf /tmp/build
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: nanasess/setup-chromedriver@v2
      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 ${{ env.HOST }}" | sudo tee -a /etc/hosts
      - name: Build containers
        timeout-minutes: 5
        run: |
          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} build
          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} up -d
      - name: Run Behat
        run: |
          chromedriver --allowed-ips="" --allowed-origins="*" &
          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} exec -T app bash -c 'bin/phing test_prepare && bin/phing testing_php_end2end -D env=test'
      - name: Clean up
        if: ${{ always() }}
        run: |
          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} down --remove-orphans --volumes
          docker rmi -f app

  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    needs:
      - code-style
      - phpunit
      - behat
    if: ${{ success() && github.actor != 'renovate[bot]' }}
    steps:
      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: build